spring:
  cloud:
    gateway:
      mvc:
        routes:

          - id: user-service
            uri: http://localhost:8081
            predicates:
              - Path=/api/users/**
            filters:
              - RewritePath=/api/users/(?<segment>.*), /user/${segment}


          - id: rooms-service
            uri: http://localhost:8082
            predicates:
              - Path=/api/rooms/**
            filters:
              - RewritePath=/api/rooms/(?<segment>.*), /room/${segment}

          - id: reservation-service
            uri: http://localhost:8083
            predicates:
              - Path=/api/reservations/**
            filters:
              - RewritePath=/api/reservations/(?<segment>.*), /reservation/${segment}

          - id: payment-service
            uri: http://localhost:8084
            predicates:
              - Path=/api/payments/**
            filters:
              - RewritePath=/api/payments/(?<segment>.*), /payment/${segment}

